name:                utf8-conversions
version:             0.1.0.1
github:              chemirea/utf8-conversions
license:             BSD3
author:              Shintaro Sakata
maintainer:          Shintaro Sakata
copyright:           2020 Shintaro Sakata
category:            Data, Codec
synopsis:            A string conversion library that assumes utf8

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/chemirea/utf8-conversions#readme>

dependencies:
- base >= 4.7 && < 5
- text >=1.0 && <1.3
- bytestring >=0.10.4 && < 0.11
- utf8-string >= 1.0 && < 1.2
- text-short >= 0.1.2 && < 0.1.4

library:
  source-dirs: src

tests:
  utf8-conversions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - utf8-conversions
